variable "project_name" {
  description = "Name of the project used for tagging and naming resources"
  type        = string
  default     = "stocklive"
}

variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "eu-west-3"
}
variable "db_password" {
  description = "Password for the RDS database (generated by Terraform random_password)"
  type        = string
  sensitive   = true
  default     = ""
}

variable "ssh_cidr" {
  description = "Allowed CIDR block for SSH access (unused - SSM used instead)"
  type        = string
  default     = "0.0.0.0/0"
}
